version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          BUNDLE_GEMFILE: <<parameters.gemfile>>

    parameters:
      gemfile:
        type: string
        description: The Gemfile to use for this build.

    steps:
      - checkout

      - restore_cache:
          keys:
            - rails-upgrades-bundle-v2-{{ checksum "<<parameters.gemfile>>.lock" }}
            - rails-upgrades-bundle-v2-

      - run:
          name: Install Bundler dependencies
          command: bundle check --gemfile=<<parameters.gemfile>> || bundle install --gemfile=<<parameters.gemfile>>

      - save_cache:
          key: rails-upgrades-bundle-v2-{{ checksum "<<parameters.gemfile>>.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - rails-upgrades-yarn-{{ checksum "yarn.lock" }}
            - rails-upgrades-yarn-

      - run:
          name: Install Yarn dependencies
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: rails-upgrades-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Set up the database
          command: bundle exec rails db:create db:schema:load

      - run:
          name: Run RSpec
          command: |
            bundle exec rspec \
              --no-color \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: test_results

workflows:
  build:
    jobs:
      - build:
          name: build-current
          gemfile: Gemfile

      - build:
          name: build-next
          gemfile: Gemfile.next
